
[dependencies]
frame-benchmarking = { branch = "polkadot-v0.9.8", default-features = false, optional = true, git = "https://github.com/paritytech/substrate" }
frame-support = { branch = "polkadot-v0.9.8", default-features = false, git = "https://github.com/paritytech/substrate" }
frame-system = { branch = "polkadot-v0.9.8", default-features = false, git = "https://github.com/paritytech/substrate" }
orml-traits = { branch = "master", default-features = false, git = "https://github.com/open-web3-stack/open-runtime-module-library" }
parity-scale-codec = { default-features = false, features = ["derive"], version = "2.0" }
sp-runtime = { branch = "polkadot-v0.9.8", default-features = false, git = "https://github.com/paritytech/substrate" }
zeitgeist-primitives = { default-features = false, path = "../../primitives" }

# Mock
orml-tokens = { branch = "master", git = "https://github.com/open-web3-stack/open-runtime-module-library", optional = true }
pallet-balances = { branch = "polkadot-v0.9.8", git = "https://github.com/paritytech/substrate", optional = true }
sp-io = { branch = "polkadot-v0.9.8", git = "https://github.com/paritytech/substrate", optional = true }

[dev-dependencies]
zrml-orderbook-v1 = { features = ["mock"], path = "." }

[features]
default = ["std"]
mock = [
    "orml-tokens",
    "pallet-balances",
    "sp-io",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks"
]
std = [
    'frame-benchmarking?/std',
    'frame-support/std',
    'frame-system/std',
    'orml-traits/std',
    'parity-scale-codec/std',
    'sp-runtime/std',
    'zeitgeist-primitives/std',
]

[package]
authors = ["Zeitgeist PM <contact@zeitgeist.pm>"]
edition = "2018"
name = "zrml-orderbook-v1"
version = "0.1.3"
