[dependencies]
parity-scale-codec = { default-features = false, features = ["derive"], version = "2.0" }
serde = { default-features = false, features = ["derive"], optional = true, version = "1.0" }
sp-api = { branch = "rococo-v1", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-runtime = { branch = "rococo-v1", default-features = false, git = "https://github.com/paritytech/substrate" }
zeitgeist-primitives = { default-features = false, path = '../../../../primitives' }

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "serde/std",
    "sp-api/std",
    "sp-runtime/std",
    "zeitgeist-primitives/std"
]

[package]
authors = ["Logan Saether <x@logansaether.com>"]
edition = "2018"
name = "zrml-swaps-runtime-api"
version = "0.1.0"