[dependencies]
parity-scale-codec = { workspace = true, features = ["derive", "max-encoded-len"] }
sp-api = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
zeitgeist-primitives = { workspace = true }

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "sp-api/std",
    "sp-runtime/std",
    "zeitgeist-primitives/std",
]

[package]
authors = ["Zeitgeist PM <contact@zeitgeist.pm>"]
edition.workspace = true
license = "GPL-3.0-or-later"
name = "zrml-swaps-runtime-api"
publish = false
version = "0.6.1"
