[[bin]]
doc = false
name = "create_pool"
path = "create_pool.rs"
test = false

[[bin]]
doc = false
name = "pool_join"
path = "pool_join.rs"
test = false

[[bin]]
doc = false
name = "pool_join_with_exact_pool_amount"
path = "pool_join_with_exact_pool_amount.rs"
test = false

[[bin]]
doc = false
name = "pool_join_with_exact_asset_amount"
path = "pool_join_with_exact_asset_amount.rs"
test = false

[[bin]]
doc = false
name = "swap_exact_amount_in"
path = "swap_exact_amount_in.rs"
test = false

[[bin]]
doc = false
name = "swap_exact_amount_out"
path = "swap_exact_amount_out.rs"
test = false

[[bin]]
doc = false
name = "pool_exit_with_exact_asset_amount"
path = "pool_exit_with_exact_asset_amount.rs"
test = false

[[bin]]
doc = false
name = "pool_exit_with_exact_pool_amount"
path = "pool_exit_with_exact_pool_amount.rs"
test = false

[[bin]]
doc = false
name = "pool_exit"
path = "pool_exit.rs"
test = false

[dependencies]
arbitrary = { features = ["derive"], version = "1.0" }
frame-support = { branch = "polkadot-v0.9.32", default-features = false, git = "https://github.com/paritytech/substrate" }
libfuzzer-sys = "0.4"
orml-traits = { branch = "polkadot-v0.9.32", default-features = false, git = "https://github.com/open-web3-stack/open-runtime-module-library" }
rand = "0.8.4"
sp-runtime = { branch = "polkadot-v0.9.32", default-features = false, git = "https://github.com/paritytech/substrate" }
zeitgeist-primitives = { features = ["mock"], path = "../../../primitives" }
zrml-swaps = { features = ["mock"], path = ".." }

[package]
authors = ["Automatically generated"]
edition = "2021"
name = "zrml-swaps-fuzz"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true
