[dependencies]
jsonrpsee = { version = "0.15.1", features = ["server", "macros"] }
parity-scale-codec = { default-features = false, version = "3.0.0" }
sp-api = { branch = "moonbeam-polkadot-v0.9.29", default-features = false, git = "https://github.com/purestake/substrate" }
sp-blockchain = { branch = "moonbeam-polkadot-v0.9.29", default-features = false, git = "https://github.com/purestake/substrate" }
sp-runtime = { branch = "moonbeam-polkadot-v0.9.29", default-features = false, git = "https://github.com/purestake/substrate" }
zeitgeist-primitives = { default-features = false, path = "../../../primitives" }
zrml-swaps-runtime-api = { default-features = false, features = ["std"], path = "../runtime-api" }

[package]
authors = ["Zeitgeist PM <contact@zeitgeist.pm>"]
edition = "2021"
name = "zrml-swaps-rpc"
version = "0.3.6"
