[dependencies]
jsonrpsee = { workspace = true, features = ["server", "macros"] }
parity-scale-codec = { workspace = true, features = ["default"] }
sp-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-runtime = { workspace = true }
zeitgeist-primitives = { workspace = true }
zrml-swaps-runtime-api = { workspace = true, features = ["default"] }

[package]
authors = ["Zeitgeist PM <contact@zeitgeist.pm>"]
edition.workspace = true
license = "GPL-3.0-or-later"
name = "zrml-swaps-rpc"
publish = false
version = "0.6.1"
