name: Rococo

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy deployment file
        uses: appleboy/scp-action@master
        with:
          host: 45.33.117.205
          key: ${{ secrets.CHACHACHA_VM_PRIVATE_KEY }}
          passphrase: ${{ secrets.CHACHACHA_VM_PASSWORD }}
          source: "scripts/parachain"
          target: "/home/ci"
          username: ci

      - name: Publish
        uses: appleboy/ssh-action@master
        with:
          host: 45.33.117.205
          key: ${{ secrets.CHACHACHA_VM_PRIVATE_KEY }}
          passphrase: ${{ secrets.CHACHACHA_VM_PASSWORD }}
          script: bash /home/ci/scripts/parachain/rococo.sh
          username: ci
