name: Try Runtime on New Tags

on:
  push:
    tags:
      - '^v[0-9]+.[0-9]+.[0-9]+(-rc[0-9]+)?$'

jobs:
  try_runtime_battery_station:
    name: Test Try Runtime
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Install build tools
        run: ./scripts/init.sh

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - run: make try-runtime-upgrade-battery-station 
  try_runtime_zeitgeist:
    name: Test Try Runtime
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Install build tools
        run: ./scripts/init.sh
        
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - run: make try-runtime-upgrade-zeitgeist 
